### ISSUE TITLE
Add file to releases page with SHA256 sums

### ISSUE THREAD

**Issue by msabramo** [PagerDuty/cronner#48]
to give users an extra sense of security that they have a real, untampered-with download.

Example: See the [`consul_0.6.4_SHA256SUMS`](https://releases.hashicorp.com/consul/0.6.4/consul_0.6.4_SHA256SUMS) file at https://releases.hashicorp.com/consul/0.6.4/

Bonus points if you sign the file with a GPG key -- e.g.: [`consul_0.6.4_SHA256SUMS.sig`](https://releases.hashicorp.com/consul/0.6.4/consul_0.6.4_SHA256SUMS.sig)

**Comment by theckman** [comment]
I've tried to get PagerDuty to give me collab access to this repo, so I've forked this project to a repo I control and plan on trying to continue development there (as-needed). I just wanted to give you a heads-up that I want to implement the SHA-256 signature at a minimum.

I'll give you a shout in this issue once my repo has the checksumming happening as part of the release process.

**Comment by theckman** [comment]
@msabramo Hey there, I've finally tackled this in my fork of `cronner` and have released `v0.4.1` which is the first to include the `sha256` file:

* https://github.com/theckman/cronner/releases/tag/v0.4.1
