### ISSUE TITLE
Feature request: statsd metric tagging

### ISSUE THREAD

**Issue by alexef** [PagerDuty/cronner#51]
Is there a reason that `-G` only tags events? It would be nice to be able to tag statsd metrics as well. If not, maybe a `-g` flag? 

I could write a PR for this.

**Comment by theckman** [comment]
Wasn't something we needed. We were using that tag to do alerting in DataDog based on emitted events. It was used just for routing failures to the right team / service owner without having to create an Event Monitor for every cron job being deployed.
